=== ZhiyunChen/Weka-Prediction/request.xsd
<?xml version = "1.0" encoding = "UTF-8"?>
<xs:schema xmlns:xs = "http://www.w3.org/2001/XMLSchema">

    <xs:element name = "request">
        <xs:complexType>
            <xs:sequence>
                <xs:element name = "patient">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name = "age"         type = "xs:string" />
                            <xs:element name = "menopause"   type = "xs:string" />
                            <xs:element name = "tumor-size"  type = "xs:string" />
                            <xs:element name = "inv-nodes"   type = "xs:string" />
                            <xs:element name = "node-caps"   type = "xs:string" />
                            <xs:element name = "deg-malig"   type = "xs:string" />
                            <xs:element name = "breast"      type = "xs:string" />
                            <xs:element name = "breast-quad" type = "xs:string" />
                            <xs:element name = "irradiat"    type = "xs:string" />
                            <xs:element name = "Class"    type = "xs:string" />
                        </xs:sequence>
                        <xs:attribute name = "patientID" type = "xs:string"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name = "requestID" type = "xs:string"/>
            <xs:attribute name = "senderIPAddress" type = "xs:string"/>
            <xs:attribute name = "receiverIPAddress" type = "xs:string"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== ZhiyunChen/Weka-Prediction/request001.xml
<?xml version="1.0" encoding="UTF-8"?>

<request requestID="Request001"
         senderIPAddress="IP1"
         receiverIPAddress="IP2"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="request.xsd">

    <patient patientID="patient#001">
        <age>40-49</age>
        <menopause>premeno</menopause>
        <tumor-size>15-19</tumor-size>
        <inv-nodes>0-2</inv-nodes>
        <node-caps>yes</node-caps>
        <deg-malig>3</deg-malig>
        <breast>right</breast>
        <breast-quad>left_up</breast-quad>
        <irradiat>no</irradiat>
        <Class>recurrence-events</Class>
    </patient>

</request>
